### PR TITLE
Add optional support for GTK+3.

### PR DESCRIPTION
**Pull request by pblaszczyk**
It provides support for GTK+3 when built with:
```bash
./configure --with-gtk3
```

### CODE REVIEW

**Comment by shantzu** [comment]
Hello,

I really appreciate your contribution, but could you please refactor this, and make it 2 separate pull requests, one with the GTK3 changes and a separate one with the code (spaces) cleanup? I would like to have these separate.
Thanks a lot!

Regards,
Cristian

**Comment by pblaszczyk** [comment]
Hello,

spaces cleanup is in #42 
Later I'll add another pr with gtk3 changes.

**Comment by shantzu** [comment]
Awesome. Thanks a lot!

**Comment by pblaszczyk** [comment]
Gtk3 changes are in #43. Closing this pr.

**Pull request closed without merging**
